/* tslint:disable */
/* eslint-disable */
/**
 * fvtt-fcb-backend
 * Backend for advanced capabilities for fvtt-campaign-builder Foundry module
 *
 * The version of the OpenAPI document: 0.0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The name previews for one name style
 * @export
 * @interface ApiNamePreviewPost200ResponsePreviewInner
 */
export interface ApiNamePreviewPost200ResponsePreviewInner {
    /**
     * Sample character names for this style
     * @type {Array<string>}
     * @memberof ApiNamePreviewPost200ResponsePreviewInner
     */
    'people'?: Array<string>;
    /**
     * Sample location names for this style
     * @type {Array<string>}
     * @memberof ApiNamePreviewPost200ResponsePreviewInner
     */
    'locations'?: Array<string>;
}

