/* tslint:disable */
/* eslint-disable */
/**
 * fvtt-fcb-backend
 * Backend for advanced capabilities for fvtt-campaign-builder Foundry module
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiNameTavernsPostRequest
 */
export interface ApiNameTavernsPostRequest {
    /**
     * Number of tavern names to generate
     * @type {number}
     * @memberof ApiNameTavernsPostRequest
     */
    'count': number;
    /**
     * Genre of the setting (e.g., fantasy, sci-fi, western)
     * @type {string}
     * @memberof ApiNameTavernsPostRequest
     */
    'genre'?: string | null;
    /**
     * The feeling or atmosphere of the world (e.g., dark, whimsical, gritty)
     * @type {string}
     * @memberof ApiNameTavernsPostRequest
     */
    'settingFeeling'?: string | null;
    /**
     * The styles of names to use
     * @type {Array<string>}
     * @memberof ApiNameTavernsPostRequest
     */
    'nameStyles'?: Array<string>;
    /**
     * The text generation model to use
     * @type {string}
     * @memberof ApiNameTavernsPostRequest
     */
    'textModel'?: ApiNameTavernsPostRequestTextModelEnum;
}

export const ApiNameTavernsPostRequestTextModelEnum = {
    Gpt4oMini: 'GPT_4o_mini',
    Claude3Haiku: 'Claude_3_haiku'
} as const;

export type ApiNameTavernsPostRequestTextModelEnum = typeof ApiNameTavernsPostRequestTextModelEnum[keyof typeof ApiNameTavernsPostRequestTextModelEnum];


