/* tslint:disable */
/* eslint-disable */
/**
 * fvtt-fcb-backend
 * Backend for advanced capabilities for fvtt-campaign-builder Foundry module
 *
 * The version of the OpenAPI document: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApiCustomGeneratePostRequestConfiguration } from './api-custom-generate-post-request-configuration';

/**
 * 
 * @export
 * @interface ApiCustomGeneratePostRequest
 */
export interface ApiCustomGeneratePostRequest {
    /**
     * The type of content that we are generating text for (location, setting, etc.)
     * @type {string}
     * @memberof ApiCustomGeneratePostRequest
     */
    'contentType': ApiCustomGeneratePostRequestContentTypeEnum;
    /**
     * The label of the field being populated
     * @type {string}
     * @memberof ApiCustomGeneratePostRequest
     */
    'fieldLabel': string;
    /**
     * The user\'s custom prompt to use for generation
     * @type {string}
     * @memberof ApiCustomGeneratePostRequest
     */
    'prompt': string;
    /**
     * Genre of the world (ex. \"fantasy\" or \"science fiction\")
     * @type {string}
     * @memberof ApiCustomGeneratePostRequest
     */
    'genre': string;
    /**
     * The feeling of the setting (ex. \"humorous\" or \"apocalyptic\")
     * @type {string}
     * @memberof ApiCustomGeneratePostRequest
     */
    'settingFeeling'?: string;
    /**
     * A TOON-encoded snippet describing the primary entity (marked `primaryEntity: true`) and all relevant world context (ancestors, referenced entities, session notes, etc.)
     * @type {string}
     * @memberof ApiCustomGeneratePostRequest
     */
    'contextSnippet': string;
    /**
     * The styles of names to use
     * @type {Array<string>}
     * @memberof ApiCustomGeneratePostRequest
     */
    'nameStyles'?: Array<string>;
    /**
     * The text generation model to use
     * @type {string}
     * @memberof ApiCustomGeneratePostRequest
     */
    'textModel'?: ApiCustomGeneratePostRequestTextModelEnum;
    /**
     * 
     * @type {ApiCustomGeneratePostRequestConfiguration}
     * @memberof ApiCustomGeneratePostRequest
     */
    'configuration'?: ApiCustomGeneratePostRequestConfiguration;
}

export const ApiCustomGeneratePostRequestContentTypeEnum = {
    Setting: 'Setting',
    Character: 'Character',
    Location: 'Location',
    Pc: 'PC',
    Organization: 'Organization',
    Campaign: 'Campaign',
    Arc: 'Arc',
    Session: 'Session',
    Front: 'Front'
} as const;

export type ApiCustomGeneratePostRequestContentTypeEnum = typeof ApiCustomGeneratePostRequestContentTypeEnum[keyof typeof ApiCustomGeneratePostRequestContentTypeEnum];
export const ApiCustomGeneratePostRequestTextModelEnum = {
    Gpt5Mini: 'GPT_5_mini',
    Gpt4oMini: 'GPT_4o_mini',
    Claude3Haiku: 'Claude_3_haiku',
    Claude5Sonnet: 'Claude_5_sonnet',
    Claude45Haiku: 'Claude_45_haiku'
} as const;

export type ApiCustomGeneratePostRequestTextModelEnum = typeof ApiCustomGeneratePostRequestTextModelEnum[keyof typeof ApiCustomGeneratePostRequestTextModelEnum];


