/* tslint:disable */
/* eslint-disable */
/**
 * fvtt-fcb-backend
 * Backend for advanced capabilities for fvtt-campaign-builder Foundry module
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApiLocationGeneratePost200ResponseDescription } from './api-location-generate-post200-response-description';

/**
 * 
 * @export
 * @interface ApiLocationGeneratePost200Response
 */
export interface ApiLocationGeneratePost200Response {
    /**
     * The generated locations\'s name
     * @type {string}
     * @memberof ApiLocationGeneratePost200Response
     */
    'name': string;
    /**
     * 
     * @type {ApiLocationGeneratePost200ResponseDescription}
     * @memberof ApiLocationGeneratePost200Response
     */
    'description': ApiLocationGeneratePost200ResponseDescription;
}

