/* tslint:disable */
/* eslint-disable */
/**
 * fvtt-fcb-backend
 * Backend for advanced capabilities for fvtt-campaign-builder Foundry module
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiNameCharactersPostRequest
 */
export interface ApiNameCharactersPostRequest {
    /**
     * Number of character names to generate
     * @type {number}
     * @memberof ApiNameCharactersPostRequest
     */
    'count': number;
    /**
     * Genre of the setting (e.g., fantasy, sci-fi, western)
     * @type {string}
     * @memberof ApiNameCharactersPostRequest
     */
    'genre'?: string | null;
    /**
     * The feeling or atmosphere of the world (e.g., dark, whimsical, gritty)
     * @type {string}
     * @memberof ApiNameCharactersPostRequest
     */
    'worldFeeling'?: string | null;
}

