/* tslint:disable */
/* eslint-disable */
/**
 * fvtt-fcb-backend
 * Backend for advanced capabilities for fvtt-campaign-builder Foundry module
 *
 * The version of the OpenAPI document: 0.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiLocationGeneratePost200Response
 */
export interface ApiLocationGeneratePost200Response {
    /**
     * The generated locations\'s name
     * @type {string}
     * @memberof ApiLocationGeneratePost200Response
     */
    'name': string;
    /**
     * A generated description of the location
     * @type {string}
     * @memberof ApiLocationGeneratePost200Response
     */
    'description': string;
}

