/* tslint:disable */
/* eslint-disable */
/**
 * fvtt-fcb-backend
 * Backend for advanced capabilities for fvtt-campaign-builder Foundry module
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiCustomGeneratePostRequest
 */
export interface ApiCustomGeneratePostRequest {
    /**
     * The type of content that we are generating text for (location, setting, etc.)
     * @type {string}
     * @memberof ApiCustomGeneratePostRequest
     */
    'contentType': ApiCustomGeneratePostRequestContentTypeEnum;
    /**
     * The entity\'s name.
     * @type {string}
     * @memberof ApiCustomGeneratePostRequest
     */
    'name': string;
    /**
     * The label of the field being populated
     * @type {string}
     * @memberof ApiCustomGeneratePostRequest
     */
    'fieldLabel': string;
    /**
     * The user\'s custom prompt to use for generation
     * @type {string}
     * @memberof ApiCustomGeneratePostRequest
     */
    'prompt': string;
    /**
     * Genre of the world (ex. \"fantasy\" or \"science fiction\")
     * @type {string}
     * @memberof ApiCustomGeneratePostRequest
     */
    'genre': string;
    /**
     * The feeling of the setting (ex. \"humorous\" or \"apocalyptic\")
     * @type {string}
     * @memberof ApiCustomGeneratePostRequest
     */
    'settingFeeling'?: string;
    /**
     * The type of the entity
     * @type {string}
     * @memberof ApiCustomGeneratePostRequest
     */
    'type'?: string;
    /**
     * The species of the entity
     * @type {string}
     * @memberof ApiCustomGeneratePostRequest
     */
    'species'?: string;
    /**
     * A brief description of the species
     * @type {string}
     * @memberof ApiCustomGeneratePostRequest
     */
    'speciesDescription'?: string;
    /**
     * The name of the parent entity
     * @type {string}
     * @memberof ApiCustomGeneratePostRequest
     */
    'parentName'?: string;
    /**
     * The type of parent entity
     * @type {string}
     * @memberof ApiCustomGeneratePostRequest
     */
    'parentType'?: string;
    /**
     * The current description of the entity\'s parent
     * @type {string}
     * @memberof ApiCustomGeneratePostRequest
     */
    'parentDescription'?: string;
    /**
     * The name of the grandparent entity
     * @type {string}
     * @memberof ApiCustomGeneratePostRequest
     */
    'grandparentName'?: string;
    /**
     * The type of grandparent entity
     * @type {string}
     * @memberof ApiCustomGeneratePostRequest
     */
    'grandparentType'?: string;
    /**
     * The current description of the entity\'s grandparent
     * @type {string}
     * @memberof ApiCustomGeneratePostRequest
     */
    'grandparentDescription'?: string;
    /**
     * A brief description of the entity to factor into the produced text
     * @type {string}
     * @memberof ApiCustomGeneratePostRequest
     */
    'description'?: string;
    /**
     * The styles of names to use
     * @type {Array<string>}
     * @memberof ApiCustomGeneratePostRequest
     */
    'nameStyles'?: Array<string>;
    /**
     * The text generation model to use
     * @type {string}
     * @memberof ApiCustomGeneratePostRequest
     */
    'textModel'?: ApiCustomGeneratePostRequestTextModelEnum;
}

export const ApiCustomGeneratePostRequestContentTypeEnum = {
    Setting: 'Setting',
    Character: 'Character',
    Location: 'Location',
    Pc: 'PC',
    Organization: 'Organization',
    Campaign: 'Campaign',
    Arc: 'Arc',
    Session: 'Session',
    Front: 'Front'
} as const;

export type ApiCustomGeneratePostRequestContentTypeEnum = typeof ApiCustomGeneratePostRequestContentTypeEnum[keyof typeof ApiCustomGeneratePostRequestContentTypeEnum];
export const ApiCustomGeneratePostRequestTextModelEnum = {
    Gpt4oMini: 'GPT_4o_mini',
    Gpt5Mini: 'GPT_5_mini',
    Claude3Haiku: 'Claude_3_haiku'
} as const;

export type ApiCustomGeneratePostRequestTextModelEnum = typeof ApiCustomGeneratePostRequestTextModelEnum[keyof typeof ApiCustomGeneratePostRequestTextModelEnum];


