/* tslint:disable */
/* eslint-disable */
/**
 * fvtt-fcb-backend
 * Backend for advanced capabilities for fvtt-campaign-builder Foundry module
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiCharacterGeneratePostRequest
 */
export interface ApiCharacterGeneratePostRequest {
    /**
     * Genre of the world (ex. \"fantasy\" or \"science fiction\")
     * @type {string}
     * @memberof ApiCharacterGeneratePostRequest
     */
    'genre': string;
    /**
     * The feeling of the world (ex. \"humorous\" or \"apocalyptic\")
     * @type {string}
     * @memberof ApiCharacterGeneratePostRequest
     */
    'worldFeeling'?: string;
    /**
     * The type of character (ex. a trade or a title)
     * @type {string}
     * @memberof ApiCharacterGeneratePostRequest
     */
    'type'?: string;
    /**
     * The species of the character (will default to human)
     * @type {string}
     * @memberof ApiCharacterGeneratePostRequest
     */
    'species'?: string;
    /**
     * A brief description of the character to factor into the produced text
     * @type {string}
     * @memberof ApiCharacterGeneratePostRequest
     */
    'briefDescription'?: string;
}

