/* tslint:disable */
/* eslint-disable */
/**
 * fvtt-fcb-backend
 * Backend for advanced capabilities for fvtt-campaign-builder Foundry module
 *
 * The version of the OpenAPI document: 0.0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiOrganizationGeneratePost200Response
 */
export interface ApiOrganizationGeneratePost200Response {
    /**
     * The generated organizations\'s name
     * @type {string}
     * @memberof ApiOrganizationGeneratePost200Response
     */
    'name': string;
    /**
     * A generated description of the organization
     * @type {string}
     * @memberof ApiOrganizationGeneratePost200Response
     */
    'description': string;
}

