/* tslint:disable */
/* eslint-disable */
/**
 * fvtt-fcb-backend
 * Backend for advanced capabilities for fvtt-campaign-builder Foundry module
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiModelsImageGet200ResponseModelsInner
 */
export interface ApiModelsImageGet200ResponseModelsInner {
    /**
     * 
     * @type {string}
     * @memberof ApiModelsImageGet200ResponseModelsInner
     */
    'id': ApiModelsImageGet200ResponseModelsInnerIdEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiModelsImageGet200ResponseModelsInner
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ApiModelsImageGet200ResponseModelsInner
     */
    'description': string;
}

export const ApiModelsImageGet200ResponseModelsInnerIdEnum = {
    MinimaxImage: 'Minimax_Image',
    Flux11Pro: 'Flux_1_1_Pro',
    FluxPro: 'Flux_Pro',
    FluxSchnellLora: 'Flux_Schnell_Lora'
} as const;

export type ApiModelsImageGet200ResponseModelsInnerIdEnum = typeof ApiModelsImageGet200ResponseModelsInnerIdEnum[keyof typeof ApiModelsImageGet200ResponseModelsInnerIdEnum];


