/* tslint:disable */
/* eslint-disable */
/**
 * fvtt-fcb-backend
 * Backend for advanced capabilities for fvtt-campaign-builder Foundry module
 *
 * The version of the OpenAPI document: 0.0.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApiNamePreviewPost200ResponsePreviewInner } from './api-name-preview-post200-response-preview-inner';

/**
 * 
 * @export
 * @interface ApiNamePreviewPost200Response
 */
export interface ApiNamePreviewPost200Response {
    /**
     * Array of objects containing sample names corresponding to passed name styles
     * @type {Array<ApiNamePreviewPost200ResponsePreviewInner>}
     * @memberof ApiNamePreviewPost200Response
     */
    'preview': Array<ApiNamePreviewPost200ResponsePreviewInner>;
}

