/* tslint:disable */
/* eslint-disable */
/**
 * fvtt-fcb-backend
 * Backend for advanced capabilities for fvtt-campaign-builder Foundry module
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiLocationGeneratePostRequest
 */
export interface ApiLocationGeneratePostRequest {
    /**
     * Genre of the world (ex. \"fantasy\" or \"science fiction\")
     * @type {string}
     * @memberof ApiLocationGeneratePostRequest
     */
    'genre': string;
    /**
     * The feeling of the setting (ex. \"humorous\" or \"apocalyptic\")
     * @type {string}
     * @memberof ApiLocationGeneratePostRequest
     */
    'settingFeeling'?: string;
    /**
     * The type of location (ex. \"town\" or \"kingdom\" or \"swamp\")
     * @type {string}
     * @memberof ApiLocationGeneratePostRequest
     */
    'type'?: string;
    /**
     * The generated location\'s name.  If blank, one will be generated (text gen only)
     * @type {string}
     * @memberof ApiLocationGeneratePostRequest
     */
    'name'?: string;
    /**
     * A brief description of the location to factor into the produced text
     * @type {string}
     * @memberof ApiLocationGeneratePostRequest
     */
    'briefDescription'?: string;
    /**
     * The type of the parent location
     * @type {string}
     * @memberof ApiLocationGeneratePostRequest
     */
    'parentName'?: string;
    /**
     * The type of parent location
     * @type {string}
     * @memberof ApiLocationGeneratePostRequest
     */
    'parentType'?: string;
    /**
     * The current description of the location\'s parent
     * @type {string}
     * @memberof ApiLocationGeneratePostRequest
     */
    'parentDescription'?: string;
    /**
     * The type of the grandparent location
     * @type {string}
     * @memberof ApiLocationGeneratePostRequest
     */
    'grandparentName'?: string;
    /**
     * The type of grandparent location
     * @type {string}
     * @memberof ApiLocationGeneratePostRequest
     */
    'grandparentType'?: string;
    /**
     * The current description of the location\'s grandparent
     * @type {string}
     * @memberof ApiLocationGeneratePostRequest
     */
    'grandparentDescription'?: string;
    /**
     * The number of paragraphs to produce in the output when using a long description
     * @type {number}
     * @memberof ApiLocationGeneratePostRequest
     */
    'longDescriptionParagraphs'?: number;
    /**
     * The styles of names to use
     * @type {Array<string>}
     * @memberof ApiLocationGeneratePostRequest
     */
    'nameStyles'?: Array<string>;
    /**
     * The text generation model to use
     * @type {string}
     * @memberof ApiLocationGeneratePostRequest
     */
    'textModel'?: ApiLocationGeneratePostRequestTextModelEnum;
}

export const ApiLocationGeneratePostRequestTextModelEnum = {
    Gpt4oMini: 'GPT_4o_mini',
    Claude3Haiku: 'Claude_3_haiku'
} as const;

export type ApiLocationGeneratePostRequestTextModelEnum = typeof ApiLocationGeneratePostRequestTextModelEnum[keyof typeof ApiLocationGeneratePostRequestTextModelEnum];


