/* tslint:disable */
/* eslint-disable */
/**
 * fvtt-fcb-backend
 * Backend for advanced capabilities for fvtt-campaign-builder Foundry module
 *
 * The version of the OpenAPI document: 0.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiCharacterGenerateImagePost200Response
 */
export interface ApiCharacterGenerateImagePost200Response {
    /**
     * The path of the new image
     * @type {string}
     * @memberof ApiCharacterGenerateImagePost200Response
     */
    'filePath': string;
}

