/* tslint:disable */
/* eslint-disable */
/**
 * fvtt-fcb-backend
 * Backend for advanced capabilities for fvtt-campaign-builder Foundry module
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiOrganizationGeneratePost200ResponseDescription
 */
export interface ApiOrganizationGeneratePost200ResponseDescription {
    /**
     * Quick notes useful during game sessions
     * @type {string}
     * @memberof ApiOrganizationGeneratePost200ResponseDescription
     */
    'roleplayNotes': string;
    /**
     * A long, detailed description of the organization.
     * @type {string}
     * @memberof ApiOrganizationGeneratePost200ResponseDescription
     */
    'long': string;
}

