/* tslint:disable */
/* eslint-disable */
/**
 * fvtt-fcb-backend
 * Backend for advanced capabilities for fvtt-campaign-builder Foundry module
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApiCustomGenerateImagePostRequestImageConfiguration } from './api-custom-generate-image-post-request-image-configuration';

/**
 * 
 * @export
 * @interface ApiCustomGenerateImagePostRequest
 */
export interface ApiCustomGenerateImagePostRequest {
    /**
     * The type of content that we are generating text for (location, setting, etc.)
     * @type {string}
     * @memberof ApiCustomGenerateImagePostRequest
     */
    'contentType': ApiCustomGenerateImagePostRequestContentTypeEnum;
    /**
     * The entity\'s name.
     * @type {string}
     * @memberof ApiCustomGenerateImagePostRequest
     */
    'name': string;
    /**
     * The user\'s custom prompt to use for generation
     * @type {string}
     * @memberof ApiCustomGenerateImagePostRequest
     */
    'prompt': string;
    /**
     * Genre of the world (ex. \"fantasy\" or \"science fiction\")
     * @type {string}
     * @memberof ApiCustomGenerateImagePostRequest
     */
    'genre': string;
    /**
     * The feeling of the setting (ex. \"humorous\" or \"apocalyptic\")
     * @type {string}
     * @memberof ApiCustomGenerateImagePostRequest
     */
    'settingFeeling'?: string;
    /**
     * The type of the entity
     * @type {string}
     * @memberof ApiCustomGenerateImagePostRequest
     */
    'type'?: string;
    /**
     * The species of the entity
     * @type {string}
     * @memberof ApiCustomGenerateImagePostRequest
     */
    'species'?: string;
    /**
     * A brief description of the species
     * @type {string}
     * @memberof ApiCustomGenerateImagePostRequest
     */
    'speciesDescription'?: string;
    /**
     * The name of the parent entity
     * @type {string}
     * @memberof ApiCustomGenerateImagePostRequest
     */
    'parentName'?: string;
    /**
     * The type of parent entity
     * @type {string}
     * @memberof ApiCustomGenerateImagePostRequest
     */
    'parentType'?: string;
    /**
     * The current description of the entity\'s parent
     * @type {string}
     * @memberof ApiCustomGenerateImagePostRequest
     */
    'parentDescription'?: string;
    /**
     * The name of the grandparent entity
     * @type {string}
     * @memberof ApiCustomGenerateImagePostRequest
     */
    'grandparentName'?: string;
    /**
     * The type of grandparent entity
     * @type {string}
     * @memberof ApiCustomGenerateImagePostRequest
     */
    'grandparentType'?: string;
    /**
     * The current description of the entity\'s grandparent
     * @type {string}
     * @memberof ApiCustomGenerateImagePostRequest
     */
    'grandparentDescription'?: string;
    /**
     * A brief description of the entity to factor into the produced text
     * @type {string}
     * @memberof ApiCustomGenerateImagePostRequest
     */
    'description'?: string;
    /**
     * The text generation model to use
     * @type {string}
     * @memberof ApiCustomGenerateImagePostRequest
     */
    'textModel'?: ApiCustomGenerateImagePostRequestTextModelEnum;
    /**
     * The image generation model to use
     * @type {string}
     * @memberof ApiCustomGenerateImagePostRequest
     */
    'imageModel'?: ApiCustomGenerateImagePostRequestImageModelEnum;
    /**
     * 
     * @type {ApiCustomGenerateImagePostRequestImageConfiguration}
     * @memberof ApiCustomGenerateImagePostRequest
     */
    'imageConfiguration'?: ApiCustomGenerateImagePostRequestImageConfiguration;
}

export const ApiCustomGenerateImagePostRequestContentTypeEnum = {
    Setting: 'Setting',
    Character: 'Character',
    Location: 'Location',
    Pc: 'PC',
    Organization: 'Organization',
    Campaign: 'Campaign',
    Arc: 'Arc',
    Session: 'Session',
    Front: 'Front'
} as const;

export type ApiCustomGenerateImagePostRequestContentTypeEnum = typeof ApiCustomGenerateImagePostRequestContentTypeEnum[keyof typeof ApiCustomGenerateImagePostRequestContentTypeEnum];
export const ApiCustomGenerateImagePostRequestTextModelEnum = {
    Gpt5Mini: 'GPT_5_mini',
    Gpt4oMini: 'GPT_4o_mini',
    Claude3Haiku: 'Claude_3_haiku'
} as const;

export type ApiCustomGenerateImagePostRequestTextModelEnum = typeof ApiCustomGenerateImagePostRequestTextModelEnum[keyof typeof ApiCustomGenerateImagePostRequestTextModelEnum];
export const ApiCustomGenerateImagePostRequestImageModelEnum = {
    MinimaxImage: 'Minimax_Image',
    Flux11Pro: 'Flux_1_1_Pro',
    FluxPro: 'Flux_Pro',
    FluxSchnellLora: 'Flux_Schnell_Lora'
} as const;

export type ApiCustomGenerateImagePostRequestImageModelEnum = typeof ApiCustomGenerateImagePostRequestImageModelEnum[keyof typeof ApiCustomGenerateImagePostRequestImageModelEnum];


