/* tslint:disable */
/* eslint-disable */
/**
 * fvtt-fcb-backend
 * Backend for advanced capabilities for fvtt-campaign-builder Foundry module
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApiCharacterGeneratePost200ResponseDescription } from './api-character-generate-post200-response-description';

/**
 * 
 * @export
 * @interface ApiCharacterGeneratePost200Response
 */
export interface ApiCharacterGeneratePost200Response {
    /**
     * The generated character\'s name
     * @type {string}
     * @memberof ApiCharacterGeneratePost200Response
     */
    'name': string;
    /**
     * 
     * @type {ApiCharacterGeneratePost200ResponseDescription}
     * @memberof ApiCharacterGeneratePost200Response
     */
    'description': ApiCharacterGeneratePost200ResponseDescription;
}

