/* tslint:disable */
/* eslint-disable */
/**
 * fvtt-fcb-backend
 * Backend for advanced capabilities for fvtt-campaign-builder Foundry module
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiLocationGenerateImagePostRequest
 */
export interface ApiLocationGenerateImagePostRequest {
    /**
     * Genre of the world (ex. \"fantasy\" or \"science fiction\")
     * @type {string}
     * @memberof ApiLocationGenerateImagePostRequest
     */
    'genre': string;
    /**
     * The feeling of the setting (ex. \"humorous\" or \"apocalyptic\")
     * @type {string}
     * @memberof ApiLocationGenerateImagePostRequest
     */
    'settingFeeling'?: string;
    /**
     * The type of location (ex. \"town\" or \"kingdom\" or \"swamp\")
     * @type {string}
     * @memberof ApiLocationGenerateImagePostRequest
     */
    'type'?: string;
    /**
     * The generated location\'s name.  If blank, one will be generated (text gen only)
     * @type {string}
     * @memberof ApiLocationGenerateImagePostRequest
     */
    'name'?: string;
    /**
     * A brief description of the location to factor into the produced text
     * @type {string}
     * @memberof ApiLocationGenerateImagePostRequest
     */
    'briefDescription'?: string;
    /**
     * The namew of the parent location
     * @type {string}
     * @memberof ApiLocationGenerateImagePostRequest
     */
    'parentName'?: string;
    /**
     * The type of parent location
     * @type {string}
     * @memberof ApiLocationGenerateImagePostRequest
     */
    'parentType'?: string;
    /**
     * The current description of the location\'s parent
     * @type {string}
     * @memberof ApiLocationGenerateImagePostRequest
     */
    'parentDescription'?: string;
    /**
     * The type of the grandparent location
     * @type {string}
     * @memberof ApiLocationGenerateImagePostRequest
     */
    'grandparentName'?: string;
    /**
     * The type of grandparent location
     * @type {string}
     * @memberof ApiLocationGenerateImagePostRequest
     */
    'grandparentType'?: string;
    /**
     * The current description of the location\'s grandparent
     * @type {string}
     * @memberof ApiLocationGenerateImagePostRequest
     */
    'grandparentDescription'?: string;
    /**
     * The number of paragraphs to produce in the output when using a long description
     * @type {number}
     * @memberof ApiLocationGenerateImagePostRequest
     */
    'longDescriptionParagraphs'?: number;
    /**
     * The styles of names to use
     * @type {Array<string>}
     * @memberof ApiLocationGenerateImagePostRequest
     */
    'nameStyles'?: Array<string>;
    /**
     * The text generation model to use
     * @type {string}
     * @memberof ApiLocationGenerateImagePostRequest
     */
    'textModel'?: ApiLocationGenerateImagePostRequestTextModelEnum;
    /**
     * The image generation model to use
     * @type {string}
     * @memberof ApiLocationGenerateImagePostRequest
     */
    'imageModel'?: ApiLocationGenerateImagePostRequestImageModelEnum;
}

export const ApiLocationGenerateImagePostRequestTextModelEnum = {
    Gpt4oMini: 'GPT_4o_mini',
    Gpt5Mini: 'GPT_5_mini',
    Claude3Haiku: 'Claude_3_haiku'
} as const;

export type ApiLocationGenerateImagePostRequestTextModelEnum = typeof ApiLocationGenerateImagePostRequestTextModelEnum[keyof typeof ApiLocationGenerateImagePostRequestTextModelEnum];
export const ApiLocationGenerateImagePostRequestImageModelEnum = {
    MinimaxImage: 'Minimax_Image',
    Flux11Pro: 'Flux_1_1_Pro',
    FluxPro: 'Flux_Pro',
    FluxSchnellLora: 'Flux_Schnell_Lora'
} as const;

export type ApiLocationGenerateImagePostRequestImageModelEnum = typeof ApiLocationGenerateImagePostRequestImageModelEnum[keyof typeof ApiLocationGenerateImagePostRequestImageModelEnum];


