/* tslint:disable */
/* eslint-disable */
/**
 * fvtt-fcb-backend
 * Backend for advanced capabilities for fvtt-campaign-builder Foundry module
 *
 * The version of the OpenAPI document: 0.0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiNamePreviewPostRequest
 */
export interface ApiNamePreviewPostRequest {
    /**
     * List of name styles to preview
     * @type {Array<string>}
     * @memberof ApiNamePreviewPostRequest
     */
    'nameStyles': Array<string>;
    /**
     * Genre of the setting (e.g., fantasy, sci-fi, western)
     * @type {string}
     * @memberof ApiNamePreviewPostRequest
     */
    'genre'?: string | null;
    /**
     * The feeling or atmosphere of the world (e.g., dark, whimsical, gritty)
     * @type {string}
     * @memberof ApiNamePreviewPostRequest
     */
    'worldFeeling'?: string | null;
}

