/* tslint:disable */
/* eslint-disable */
/**
 * fvtt-fcb-backend
 * Backend for advanced capabilities for fvtt-campaign-builder Foundry module
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiModelsTextGet200ResponseModelsInner
 */
export interface ApiModelsTextGet200ResponseModelsInner {
    /**
     * 
     * @type {string}
     * @memberof ApiModelsTextGet200ResponseModelsInner
     */
    'id': ApiModelsTextGet200ResponseModelsInnerIdEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiModelsTextGet200ResponseModelsInner
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ApiModelsTextGet200ResponseModelsInner
     */
    'description': string;
}

export const ApiModelsTextGet200ResponseModelsInnerIdEnum = {
    Gpt5Mini: 'GPT_5_mini',
    Gpt4oMini: 'GPT_4o_mini',
    Claude3Haiku: 'Claude_3_haiku'
} as const;

export type ApiModelsTextGet200ResponseModelsInnerIdEnum = typeof ApiModelsTextGet200ResponseModelsInnerIdEnum[keyof typeof ApiModelsTextGet200ResponseModelsInnerIdEnum];


