/* tslint:disable */
/* eslint-disable */
/**
 * fvtt-fcb-backend
 * Backend for advanced capabilities for fvtt-campaign-builder Foundry module
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiCustomGeneratePostRequestConfiguration
 */
export interface ApiCustomGeneratePostRequestConfiguration {
    /**
     * Minimum words
     * @type {number}
     * @memberof ApiCustomGeneratePostRequestConfiguration
     */
    'minWords'?: number;
    /**
     * Maximum words
     * @type {number}
     * @memberof ApiCustomGeneratePostRequestConfiguration
     */
    'maxWords'?: number;
    /**
     * Short description of the type of tone to use in the responses
     * @type {string}
     * @memberof ApiCustomGeneratePostRequestConfiguration
     */
    'tone'?: string;
    /**
     * The grammatical tense to use
     * @type {string}
     * @memberof ApiCustomGeneratePostRequestConfiguration
     */
    'tense'?: string;
    /**
     * The point of view to use
     * @type {string}
     * @memberof ApiCustomGeneratePostRequestConfiguration
     */
    'pov'?: string;
    /**
     * Content rating
     * @type {string}
     * @memberof ApiCustomGeneratePostRequestConfiguration
     */
    'contentRating'?: string;
    /**
     * Whether to include headings. Won\'t force headings, but will allow them.
     * @type {boolean}
     * @memberof ApiCustomGeneratePostRequestConfiguration
     */
    'includeHeadings'?: boolean;
    /**
     * Whether to include bullets. Won\'t force bullets, but will allow them.
     * @type {boolean}
     * @memberof ApiCustomGeneratePostRequestConfiguration
     */
    'includeBullets'?: boolean;
    /**
     * Maximum items in a list
     * @type {number}
     * @memberof ApiCustomGeneratePostRequestConfiguration
     */
    'avoidListsLongerThan'?: number;
}

