/* tslint:disable */
/* eslint-disable */
/**
 * fvtt-fcb-backend
 * Backend for advanced capabilities for fvtt-campaign-builder Foundry module
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiOrganizationGeneratePostRequest
 */
export interface ApiOrganizationGeneratePostRequest {
    /**
     * Genre of the world (ex. \"fantasy\" or \"science fiction\")
     * @type {string}
     * @memberof ApiOrganizationGeneratePostRequest
     */
    'genre': string;
    /**
     * The feeling of the world (ex. \"humorous\" or \"apocalyptic\")
     * @type {string}
     * @memberof ApiOrganizationGeneratePostRequest
     */
    'worldFeeling'?: string;
    /**
     * The type of organization (ex. \"family\" or \"cult\")
     * @type {string}
     * @memberof ApiOrganizationGeneratePostRequest
     */
    'type'?: string;
    /**
     * The generated organization\'s name.  If blank, one will be generated (text gen only)
     * @type {string}
     * @memberof ApiOrganizationGeneratePostRequest
     */
    'name'?: string;
    /**
     * A brief description of the organization to factor into the produced text
     * @type {string}
     * @memberof ApiOrganizationGeneratePostRequest
     */
    'briefDescription'?: string;
    /**
     * The type of the parent organization
     * @type {string}
     * @memberof ApiOrganizationGeneratePostRequest
     */
    'parentName'?: string;
    /**
     * The type of parent organization
     * @type {string}
     * @memberof ApiOrganizationGeneratePostRequest
     */
    'parentType'?: string;
    /**
     * The current description of the organization\'s parent
     * @type {string}
     * @memberof ApiOrganizationGeneratePostRequest
     */
    'parentDescription'?: string;
    /**
     * The type of the grandparent organization
     * @type {string}
     * @memberof ApiOrganizationGeneratePostRequest
     */
    'grandparentName'?: string;
    /**
     * The type of grandparent organization
     * @type {string}
     * @memberof ApiOrganizationGeneratePostRequest
     */
    'grandparentType'?: string;
    /**
     * The current description of the organization\'s grandparent
     * @type {string}
     * @memberof ApiOrganizationGeneratePostRequest
     */
    'grandparentDescription'?: string;
}

