/* tslint:disable */
/* eslint-disable */
/**
 * fvtt-fcb-backend
 * Backend for advanced capabilities for fvtt-campaign-builder Foundry module
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApiModelsImageGet200ResponseModelsInner } from './api-models-image-get200-response-models-inner';

/**
 * 
 * @export
 * @interface ApiModelsImageGet200Response
 */
export interface ApiModelsImageGet200Response {
    /**
     * 
     * @type {Array<ApiModelsImageGet200ResponseModelsInner>}
     * @memberof ApiModelsImageGet200Response
     */
    'models': Array<ApiModelsImageGet200ResponseModelsInner>;
}

