/* tslint:disable */
/* eslint-disable */
/**
 * fvtt-fcb-backend
 * Backend for advanced capabilities for fvtt-campaign-builder Foundry module
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApiModelsTextGet200ResponseModelsInner } from './api-models-text-get200-response-models-inner';

/**
 * 
 * @export
 * @interface ApiModelsTextGet200Response
 */
export interface ApiModelsTextGet200Response {
    /**
     * 
     * @type {Array<ApiModelsTextGet200ResponseModelsInner>}
     * @memberof ApiModelsTextGet200Response
     */
    'models': Array<ApiModelsTextGet200ResponseModelsInner>;
}

