/* tslint:disable */
/* eslint-disable */
/**
 * fvtt-fcb-backend
 * Backend for advanced capabilities for fvtt-campaign-builder Foundry module
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiCustomGenerateImagePostRequestImageConfiguration
 */
export interface ApiCustomGenerateImagePostRequestImageConfiguration {
    /**
     * High-level art style / aesthetic (ex. \"watercolor\", \"hand-drawn\", \"oil painting\", \"pixel art\"). Default: \"\" (no preference)
     * @type {string}
     * @memberof ApiCustomGenerateImagePostRequestImageConfiguration
     */
    'artStyle'?: string;
    /**
     * Medium / technique (ex. \"ink\", \"gouache\", \"pencil sketch\", \"3D render\"). Default: \"\" (no preference)
     * @type {string}
     * @memberof ApiCustomGenerateImagePostRequestImageConfiguration
     */
    'medium'?: string;
    /**
     * Model-specific style hint (ex. \"cinematic\", \"anime\", \"comic\"). Default: \"\" (no preference)
     * @type {string}
     * @memberof ApiCustomGenerateImagePostRequestImageConfiguration
     */
    'modelStyle'?: string;
    /**
     * Content rating / safety level (ex. \"G\", \"PG\", \"PG-13\", \"R\"). Default: \"PG-13\"
     * @type {string}
     * @memberof ApiCustomGenerateImagePostRequestImageConfiguration
     */
    'contentRating'?: string;
    /**
     * Composition direction (ex. \"close-up portrait\", \"wide establishing shot\", \"rule of thirds\"). Default: \"\" (no preference)
     * @type {string}
     * @memberof ApiCustomGenerateImagePostRequestImageConfiguration
     */
    'composition'?: string;
    /**
     * Lighting direction (ex. \"golden hour\", \"moody rim light\", \"soft studio lighting\"). Default: \"\" (no preference)
     * @type {string}
     * @memberof ApiCustomGenerateImagePostRequestImageConfiguration
     */
    'lighting'?: string;
    /**
     * Color palette direction (ex. \"muted earth tones\", \"vibrant neon\"). Default: \"\" (no preference)
     * @type {string}
     * @memberof ApiCustomGenerateImagePostRequestImageConfiguration
     */
    'colorPalette'?: string;
    /**
     * Camera framing / lens hints (ex. \"35mm\", \"telephoto\", \"shallow depth of field\"). Default: \"\" (no preference)
     * @type {string}
     * @memberof ApiCustomGenerateImagePostRequestImageConfiguration
     */
    'camera'?: string;
    /**
     * Mood / emotion (ex. \"ominous\", \"whimsical\", \"serene\"). Default: \"\" (no preference)
     * @type {string}
     * @memberof ApiCustomGenerateImagePostRequestImageConfiguration
     */
    'mood'?: string;
    /**
     * Things to explicitly avoid in the image (ex. \"text, watermark, extra limbs\"). Default: \"\" (no negative prompt)
     * @type {string}
     * @memberof ApiCustomGenerateImagePostRequestImageConfiguration
     */
    'negativePrompt'?: string;
    /**
     * Advanced provider/model options passed through to the image generator (model-specific). Default: {}
     * @type {{ [key: string]: any; }}
     * @memberof ApiCustomGenerateImagePostRequestImageConfiguration
     */
    'providerOptions'?: { [key: string]: any; };
}

