/* tslint:disable */
/* eslint-disable */
/**
 * fvtt-fcb-backend
 * Backend for advanced capabilities for fvtt-campaign-builder Foundry module
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiCustomGeneratePost200Response
 */
export interface ApiCustomGeneratePost200Response {
    /**
     * The generated response
     * @type {string}
     * @memberof ApiCustomGeneratePost200Response
     */
    'response': string;
}

