/* tslint:disable */
/* eslint-disable */
/**
 * fvtt-fcb-backend
 * Backend for advanced capabilities for fvtt-campaign-builder Foundry module
 *
 * The version of the OpenAPI document: 0.0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApiPollEmailTodoGet200ResponseItemsInner } from './api-poll-email-todo-get200-response-items-inner';

/**
 * 
 * @export
 * @interface ApiPollEmailTodoGet200Response
 */
export interface ApiPollEmailTodoGet200Response {
    /**
     * 
     * @type {Array<ApiPollEmailTodoGet200ResponseItemsInner>}
     * @memberof ApiPollEmailTodoGet200Response
     */
    'items': Array<ApiPollEmailTodoGet200ResponseItemsInner>;
}

