/* tslint:disable */
/* eslint-disable */
/**
 * fvtt-fcb-backend
 * Backend for advanced capabilities for fvtt-campaign-builder Foundry module
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiOrganizationGenerateImagePostRequest
 */
export interface ApiOrganizationGenerateImagePostRequest {
    /**
     * Genre of the world (ex. \"fantasy\" or \"science fiction\")
     * @type {string}
     * @memberof ApiOrganizationGenerateImagePostRequest
     */
    'genre': string;
    /**
     * The feeling of the setting (ex. \"humorous\" or \"apocalyptic\")
     * @type {string}
     * @memberof ApiOrganizationGenerateImagePostRequest
     */
    'settingFeeling'?: string;
    /**
     * The type of organization (ex. \"family\" or \"cult\")
     * @type {string}
     * @memberof ApiOrganizationGenerateImagePostRequest
     */
    'type'?: string;
    /**
     * The generated organization\'s name.  If blank, one will be generated (text gen only)
     * @type {string}
     * @memberof ApiOrganizationGenerateImagePostRequest
     */
    'name'?: string;
    /**
     * A brief description of the organization to factor into the produced text
     * @type {string}
     * @memberof ApiOrganizationGenerateImagePostRequest
     */
    'briefDescription'?: string;
    /**
     * The name of the parent organization
     * @type {string}
     * @memberof ApiOrganizationGenerateImagePostRequest
     */
    'parentName'?: string;
    /**
     * The type of parent organization
     * @type {string}
     * @memberof ApiOrganizationGenerateImagePostRequest
     */
    'parentType'?: string;
    /**
     * The current description of the organization\'s parent
     * @type {string}
     * @memberof ApiOrganizationGenerateImagePostRequest
     */
    'parentDescription'?: string;
    /**
     * The number of paragraphs to produce in the output when using a long description
     * @type {number}
     * @memberof ApiOrganizationGenerateImagePostRequest
     */
    'longDescriptionParagraphs'?: number;
    /**
     * The type of the grandparent organization
     * @type {string}
     * @memberof ApiOrganizationGenerateImagePostRequest
     */
    'grandparentName'?: string;
    /**
     * The type of grandparent organization
     * @type {string}
     * @memberof ApiOrganizationGenerateImagePostRequest
     */
    'grandparentType'?: string;
    /**
     * The current description of the organization\'s grandparent
     * @type {string}
     * @memberof ApiOrganizationGenerateImagePostRequest
     */
    'grandparentDescription'?: string;
    /**
     * The styles of names to use
     * @type {Array<string>}
     * @memberof ApiOrganizationGenerateImagePostRequest
     */
    'nameStyles'?: Array<string>;
    /**
     * The text generation model to use
     * @type {string}
     * @memberof ApiOrganizationGenerateImagePostRequest
     */
    'textModel'?: ApiOrganizationGenerateImagePostRequestTextModelEnum;
    /**
     * The image generation model to use
     * @type {string}
     * @memberof ApiOrganizationGenerateImagePostRequest
     */
    'imageModel'?: ApiOrganizationGenerateImagePostRequestImageModelEnum;
}

export const ApiOrganizationGenerateImagePostRequestTextModelEnum = {
    Gpt4oMini: 'GPT_4o_mini',
    Gpt5Mini: 'GPT_5_mini',
    Claude3Haiku: 'Claude_3_haiku'
} as const;

export type ApiOrganizationGenerateImagePostRequestTextModelEnum = typeof ApiOrganizationGenerateImagePostRequestTextModelEnum[keyof typeof ApiOrganizationGenerateImagePostRequestTextModelEnum];
export const ApiOrganizationGenerateImagePostRequestImageModelEnum = {
    MinimaxImage: 'Minimax_Image',
    Flux11Pro: 'Flux_1_1_Pro',
    FluxPro: 'Flux_Pro',
    FluxSchnellLora: 'Flux_Schnell_Lora'
} as const;

export type ApiOrganizationGenerateImagePostRequestImageModelEnum = typeof ApiOrganizationGenerateImagePostRequestImageModelEnum[keyof typeof ApiOrganizationGenerateImagePostRequestImageModelEnum];


