/* tslint:disable */
/* eslint-disable */
/**
 * fvtt-fcb-backend
 * Backend for advanced capabilities for fvtt-campaign-builder Foundry module
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApiOrganizationGeneratePost200ResponseDescription } from './api-organization-generate-post200-response-description';

/**
 * 
 * @export
 * @interface ApiOrganizationGeneratePost200Response
 */
export interface ApiOrganizationGeneratePost200Response {
    /**
     * The generated organizations\'s name
     * @type {string}
     * @memberof ApiOrganizationGeneratePost200Response
     */
    'name': string;
    /**
     * 
     * @type {ApiOrganizationGeneratePost200ResponseDescription}
     * @memberof ApiOrganizationGeneratePost200Response
     */
    'description': ApiOrganizationGeneratePost200ResponseDescription;
}

