/* tslint:disable */
/* eslint-disable */
/**
 * fvtt-fcb-backend
 * Backend for advanced capabilities for fvtt-campaign-builder Foundry module
 *
 * The version of the OpenAPI document: 0.0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiNameStoresPost200Response
 */
export interface ApiNameStoresPost200Response {
    /**
     * Array of generated store names
     * @type {Array<string>}
     * @memberof ApiNameStoresPost200Response
     */
    'names': Array<string>;
}

