title: World & Campaign Builder
description: A Foundry VTT module for worldbuilding and campaign management
url: "https://dovrosenberg.github.io"
baseurl: "/fvtt-campaign-builder"

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight

# Plugins
plugins:
  - jekyll-glossary_tooltip

# Glossary tooltip configuration
glossary_tooltip:
  dictionary: glossary.yml
  style: "border-bottom: 1px dotted #3eb0ef; text-decoration: none;"
  tooltip_style: "background-color: #2c2c2c; color: #fff; padding: 10px; border-radius: 5px; font-size: 14px; max-width: 300px;"

# GitHub Pages specific settings
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/



# GitHub repository
github:
  repository_url: https://github.com/dovrosenberg/fvtt-campaign-builder
  owner_name: dovrosenberg
  repository_name: fvtt-campaign-builder

# Custom footer content
footer: "Copyright &copy; 2025 Dov Rosenberg. Licensed under the Apache License, Version 2.0."