source "https://rubygems.org"

# Use the github-pages gem for GitHub Pages compatibility
gem "github-pages", group: :jekyll_plugins

# Additional dependencies
gem "webrick", "~> 1.8"
gem "faraday-retry"

# Theme
gem "just-the-docs", "0.4.2"

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Lock jekyll-sass-converter to 1.5.2 to maintain compatibility
gem "jekyll-sass-converter", "~> 1.5.2"