name: Translate Language Files

on:
  # Run automatically when en.json is updated on dev branch
  push:
    branches:
      - dev
    paths:
      - 'static/lang/en.json'
  
  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install openai

      - name: Translate to all languages
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: node .scripts/translate.js
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update translations"
          title: "Update translations"
          body-file: pr_body.txt
          branch: translations-${{ github.sha }}
          base: dev